name: prod
dependencies:
- python=3.9
- pip
# renovate datasource=conda depName=main/sqlalchemy
- sqlalchemy=1.4.3
# renovate datasource=conda depName=main/alembic
- alembic=1.7.5
- click=8.0
- pyyaml=6.0
- jinja2<3.1
- requests<2.28
- pip:
  # FastAPI
  - fastapi<=0.75
  # renovate datasource=pypi
  - pydantic[email,dotenv]==1.10.11
  # renovate datasource=pypi
  - uvicorn==0.17.6
  # DataDog
  - ddtrace==0.49.3
  - protobuf==3.20.1
  # LaunchDarkly
  - launchdarkly-server-sdk==8.1.1
  # Postgres
  - asyncpg==0.25.0
  # Kafka
  - aiokafka<=0.7.2
  # Redis
  - aioredis<1.4
  # General
  - python-jose<=3.3
  - fastjsonschema<3.0
  - httpx<=0.23
  - simpleeval<0.10
channels:
- defaults
